In [2]:
pip install sklearn

     |████████████████████████████████| 6.8 MB 4.7 MB/s eta 0:00:01
     |████████████████████████████████| 302 kB 61.7 MB/s eta 0:00:01
     |████████████████████████████████| 25.9 MB 3.1 kB/s  eta 0:00:0101
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1315 sha256=56a947aaf9ba78a6c7f6e4d6a7f3aaf98a13f745d1f49679749121f39cafbcb5
  Stored in directory: /home/jovyan/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn
Note: you may need to restart the kernel to use updated packages.


In [3]:
# Pandas is used for data manipulation
import pandas as pd

# Read in data and display first 5 rows
features = pd.read_csv('TemperatureData.csv')


# print(features.head(5))
# print('The shape of our features is:', features.shape)
# features.describe()

# Use datetime for dealing with dates
import datetime

# Get years, months, and days
years = features['Year']
months = features['Month']
days = features['Day']

# List and then convert to datetime object
dates = [str(int(year)) + '-' + str(int(month)) + '-' + str(int(day)) for year, month, day in zip(years, months, days)]
dates = [datetime.datetime.strptime(date, '%Y-%m-%d') for date in dates]


# Import matplotlib for plotting and use magic command for Jupyter Notebooks
import matplotlib.pyplot as plt

%matplotlib inline

# Set the style
plt.style.use('fivethirtyeight')

# Set up the plotting layout
#fig, (ax1, ax2, ax3) = plt.subplots(nrows=3, ncols=1, figsize = (8,8))
#fig.autofmt_xdate(rotation = 45)

# Actual max temperature measurement
#ax1.plot(dates, features['Temp'])
#ax1.set_xlabel(''); ax1.set_ylabel('Temperature (F)'); ax1.set_title('Temp')

# Temperature from 1 day ago
#ax2.plot(dates, features['Temp-1'])
#ax2.set_xlabel(''); ax2.set_ylabel('Temperature (F)'); ax2.set_title('Temp:-1')

# Temperature from 2 days ago
#ax3.plot(dates, features['Temp-2'])
#ax3.set_xlabel('Date'); ax3.set_ylabel('Temperature (F)'); ax3.set_title('Temp:-2')

#don't plot
# plt.tight_layout(pad=3)


# One-hot encode weekdays (transform weekdays to binary columns (using pandas get_dummies)
#print(pd.get_dummies(features))

features = pd.get_dummies(features)

# Use numpy to convert to arrays
import numpy as np

# create Labels array of the target variable (aka label, dependent variable)
labels = np.array(features['Temp'])

# Remove this column from the features
# axis 1 refers to the columns
features= features.drop('Temp', axis = 1)

# Saving feature names for later use
feature_list = list(features.columns)

# Convert remaining data to a numpy array (also called features)
features = np.array(features)



# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

# Train the model on training data
rf.fit(train_features, train_labels);

# Use the forest's predict method on the test data
predictions = rf.predict(test_features)

# Calculate the absolute errors
errors = abs(predictions - test_labels)

listx = np.stack((test_labels, predictions, errors), axis=1)
print(listx)

# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Training Features Shape: (273, 12)
Training Labels Shape: (273,)
Testing Features Shape: (92, 12)
Testing Labels Shape: (92,)
[[6.7000e+01 6.6483e+01 5.1700e-01]
 [3.5000e+01 3.9123e+01 4.1230e+00]
 [4.6000e+01 4.3478e+01 2.5220e+00]
 [4.5000e+01 4.8278e+01 3.2780e+00]
 [5.1000e+01 4.9971e+01 1.0290e+00]
 [6.5000e+01 6.2896e+01 2.1040e+00]
 [4.5000e+01 4.3682e+01 1.3180e+00]
 [5.3000e+01 5.2361e+01 6.3900e-01]
 [6.7000e+01 6.4445e+01 2.5550e+00]
 [5.2000e+01 4.8332e+01 3.6680e+00]
 [4.0000e+01 4.1387e+01 1.3870e+00]
 [4.7000e+01 4.7015e+01 1.5000e-02]
 [5.6000e+01 4.5210e+01 1.0790e+01]
 [4.9000e+01 4.9226e+01 2.2600e-01]
 [5.6000e+01 5.3173e+01 2.8270e+00]
 [4.4000e+01 4.7980e+01 3.9800e+00]
 [4.7000e+01 4.0980e+01 6.0200e+00]
 [4.9000e+01 5.4172e+01 5.1720e+00]
 [5.2000e+01 5.0480e+01 1.5200e+00]
 [4.3000e+01 4.4966e+01 1.9660e+00]
 [3.8000e+01 4.2930e+01 4.9300e+00]
 [5.9000e+01 5.7702e+01 1.2980e+00]
 [5.1000e+01 4.9145e+01 1.8550e+00]
 [6.3000e+01 5.6911e+01 6.0890e+00]
 [5.7000e+